--- 
- 
  hosts: wildfly 
  tasks: 
    - 
      name: "Verification presence JDK8"
      package: "name=openjdk-8-jdk-headless state=present"      
    -
      name: "Verifier l'existence du dossier wildfly"
      stat: path=/opt/wildfly-11.0.0.Final
      register: check_folder
    - 
      name: "Creation de l'utilisateur wildfly"
      user: 
        comment: "utilisateur syteme wildfly"
        home: /home/wildfly
        name: wildfly
        system: true
    -
      name: "Telechargement de l'archive wildfly"
      get_url:
        url: http://download.jboss.org/wildfly/11.0.0.Final/wildfly-11.0.0.Final.tar.gz
        dest: /opt/wildfly-11.0.0.Final.tar.gz
    -
      name: "Dezippage de l'archive wildfly"
      unarchive:
        dest: /opt/
        src: /opt/wildfly-11.0.0.Final.tar.gz
        remote_src: yes
    -
      command: "mv /opt/wildfly-11.0.0.Final /opt/wildfly"
      name: "Renommage du dossier wildfly"
      args:
        chdir: /opt
        creates: /opt/wildfly/
    -
      name: "Modification des droits du dossier /opt/wildfly"
      file:
        path: /opt/wildfly
        owner: wildfly
        group: wildfly
        mode: 0755
        state: directory
    -
      file:
        owner: wildfly
        group: wildfly
        path: /etc/wildfly
        mode: 0755 
        state: directory
      name: "Creation du repertoire wildfly dans /etc"
    - 
      name: "Déplacer wildfly.conf"
      copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf 
        dest: /etc/wildfly/wildfly.conf
        remote_src: true
    -
      name: "Déplacer wildfly.service"
      copy: 
        src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.service
        dest: /etc/systemd/system/wildfly.service
        remote_src: true
    -
      name: "Déplacer et donner les droits à launch.sh"
      copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/launch.sh
        dest: /opt/wildfly/bin
        remote_src: true
        mode: 0755
    -
      name: "Démarrage du service wildfly"
      service:
        name: wildfly
        state: started
    -
      name: "reload daemon"
      command: systemctl daemon-reload
